version: '2'

services:
  php:
    build: ./deploy/php
    volumes:
      - /var/www/html:/home
  mysql:
    build: ./deploy/mysql
    volumes:
      - /var/mysql/data:/var/lib/mysql
  redis:
    build: ./deploy/redis
  nginx:
    build: ./deploy/nginx
    ports:
      - 80:80
      - 443:443
