version: '2'

services:
  nginx:
    build: ./deploy/nginx
    ports:
      - 80:80
      - 443:443
  php:
    build: ./deploy/php
    volumes:
      - /home:/var/www/html
  redis:
    build: ./deploy/redis
